[package]
authors = ["Polymetric <polymetricofficial@gmail.com>",
           "Łukasz Jan Niemier <lukasz@niemier.pl>",
           "Jeremy Soller <jackpot51@gmail.com>",
           "Ticki <Ticki@users.noreply.github.com>"]
name = "coreutils"
version = "0.1.0"

[dependencies]
clap = "1.5.4"
